### PR TITLE
Add debian packaging

### PR DESCRIPTION
**Pull request by mcnewton**
This builds two packages:

  log-courier     - to install on end systems
  log-courier-gem - to install on the logstash system

The log-courier-gem package is experimental at best due to the
way the gem is installed/removed in postinst/prerm.

### CODE REVIEW

**Comment by driskell** [comment]
Thanks! I'll take a closer look soon

Regarding the gem package - could you remove that? Going forwards with Logstash 1.5 I'll be supporting the plugin system so you simply run from Logstash folder "bin/plugin install logstash-input-log-courier".
Rather not complicate things with gem packages and such that modify the Logstash installation.

Thanks again :)

**Comment by mcnewton** [comment]
Gem packaging removed!

**Comment by driskell** [comment]
The joys of having a directory layout enforced upon you for a single cog in a larger wheel :+1: 
I've not forgotten about this :) Just debating with myself on where to put things!

**Comment by mcnewton** [comment]
No problem - though I'm not sure what you need to put where? The Debian packaging stuff needs to be in debian/ and nowhere else, so if you move it then it'll break :-) But it is always self-contained in that directory. I think it's the same with RPMs and the spec file? Maybe they are a bit more flexible about the location.

**Comment by driskell** [comment]
The rpmbuild process involves the upstream code archive + spec file + build command. So I can stick the spec anywhere, even not have it at all, and it can still be automatically built if you have your own spec.

Seems debian insist on requiring the source is modified and the source has the package building code and files embedded within in (which makes no sense to me). It just irritates me that I can't put it with it the rpm spec in contrib without it breaking heh. I'll work something out, maybe even leaving it as is and putting up with the mess. It's like being told by WinZip you have to include a application.winzip file in your folder before you can ZIP it up.

**Comment by mcnewton** [comment]
Depends whether you call it a mess or not! :-)

If it gets picked up and pulled into Debian then there's no need to add anything to your source as they add the debian/ directory etc themselves and maintain it.

You only need to include it if you want to provide the ability to build a Debian package yourself. Which both helps people for now (as it's not in Debian) and helps people when it's in Debian as their version will always lag behind by a bit.

I think in the official Debian repository they keep the unmodified source tarball and a separate patch that adds the debian/ directory.

The other option is to just move it into contrib. Debian instructions just gain one prior step: "mv contrib/debian ."! You could even add a "make deb" like some software does which would do that (or create a symlink) as part of the process?

**Comment by driskell** [comment]
> The other option is to just move it into contrib. Debian instructions just gain one prior step: "mv contrib/debian ."! You could even add a "make deb" like some software does which would do that (or create a symlink) as part of the process?

That is what I was thinking too.

**Comment by driskell** [comment]
Just for reference, this was closed by Github when I merged it into a branch (not develop) called pull_151. I've been tweaking it and making the RPM and DEB consistent. I choose to place it in contrib/deb and just provide instructions. I'll look at a `make rpm` and `make deb` eventually, whether replacing with `fpm` or not.

I've setup a Launchpad PPA and just about ready to upload and test a Ubuntu Vivid release too. Once tested I'll update README and maybe see if it will install onto Debian too.

**Comment by driskell** [comment]
Thanks for the starting point - it's helped greatly and I appreciate it!

**Comment by driskell** [comment]
And we're nearly done :)

[NEEDSBUILD]	i386 build of log-courier 1.6-2 in ubuntu trusty RELEASE
Pending (2505)
[NEEDSBUILD]	amd64 build of log-courier 1.6-2 in ubuntu trusty RELEASE
Pending (2505)

Thanks again! :+1:

**Pull request closed without merging**
