### PR TITLE
Implement SRV record lookup for #85

### PR DESCRIPTION
**Pull request by driskell**
- [x] Check configuration regarding use in ZMQ transports

### CODE REVIEW

**Comment by blalor** [comment]
This looks pretty good, but I think hard-coding the service is a bit too prescriptive.  If instead the config syntax supported `@_courier._tcp.service.consul` and passed empty strings to the `service` and `proto` arguments of [`net.LookupSRV`](http://golang.org/pkg/net/#LookupSRV) I think it would be more flexible and readable.  That should still allow resolving `@_courier._tcp` against the host's current domain (close to what the current functionality is in this PR), as well as allowing any other service name to be given.

**Comment by driskell** [comment]
@blalor I can't really think of a good reason why the service and proto would need to be configurable. Though a mail server called Courier exists as we all know... so I guess that could conflict if something was already set to use that service name.

I think if they needed to be configurable though it wouldn't be in the servers declaration, and would be separate parameters. Or at the very worst, in the servers declaration somehow but without the underscores and "tcp" as those are irrelevant technical details.

Is customising it a specific requirement of yours?

**Comment by blalor** [comment]
I'd say it is a specific requirement, actually.  Imagine an environment with a flat DNS namespace that has multiple logstash instances; perhaps database logs get shipped to one instance while web server logs go to another, or they're segmented for PCI compliance or by environment.  In that case you might want to specify `@_courier._web.example.com` and `@_courier._db.example.com`, or `@_dev-courier._tcp.example.com`, etc.

This ties in with Consul and how it exposes registered services via its [DNS interface](http://www.consul.io/docs/agent/dns.html).  Specifically, the protocol is (ab)used to specify tags to select particular instances of a service.

**Comment by driskell** [comment]
Ok I might be convinced :-)

I can see the RFC is just one way of structuring the SRV records and you can have an SRV on any address. I'll do some changes soon. Thanks for feeding back!

**Comment by driskell** [comment]
OK, so RFC 2782 is the default still, but there's now an option to change the service used (instead of "courier") and one to turn off RFC 2782 altogether.

So you can happily set "rfc 2782 srv" to false and specify "@courier.service.consul" for example. Or leave the rfc setting default and specify "@service.consul" which will trigger a request for `_courier._tcp.service.consul` as before.

**Comment by driskell** [comment]
@blalor Let me know what your thoughts are on these latest changes. Thanks

**Comment by blalor** [comment]
That looks really good to me.  Not sure I see the need for keeping the strict RFC-style lookup around, but the code to do so is minimal.  Can this be extended to the other transports, like zmq, as well?

**Pull request merged**
