### PR TITLE
fix incorrect logic on log level documentation

### PR DESCRIPTION
**Pull request by tedder**

### CODE REVIEW

**Comment by driskell** [comment]
Thanks for the contribution! Though I'm not so sure. I read it like so:

"critical" is the maximum level of detail you'll get.
"info" is the maximum level of detail you'll get.
As in - the more you go towards "debug", the higher the level of detail.

"warning" is the minimum level of detail you'll get - to me this implies you'll get more detail than "warning"

Essentially the option "caps" the logging level, so I think maximum the right term here. Do you see it differently?

**Comment by tedder** [comment]
Hmm, I guess it's terminology, depending on if important logs are considered at the "top" (lexicographically) or at the bottom. Lemme look around to see how it's used elsewhere- it's likely this is just my brain that misparsed it.

**Comment by tedder** [comment]
Here are selected results from a google search, these are in support of my understanding of "minimum log level":

* http://docs-legacy.fortinet.com/fcache/olh/2-2-0/index.html#page/FortiCache-v2.2-Online-Help/1100_Logging.12.2.html
* http://stackoverflow.com/questions/4312621/why-dont-info-level-messages-get-logged-when-minimum-level-is-debug
* https://logging.apache.org/log4j/1.2/apidocs/org/apache/log4j/Priority.html#isGreaterOrEqual(org.apache.log4j.Priority)
* http://mojolicio.us/perldoc/Mojo/Log#SYNOPSIS
* https://logging.apache.org/log4j/1.2/apidocs/org/apache/log4j/Level.html#OFF

doesn't support it one way or the other:

* http://stackoverflow.com/questions/9552754/minimum-log-level-compiled

after some headscratching, this supports the "minimum":

* https://www.axigen.com/knowledgebase/How-to-set-the-maximum-log-level-for-all-logged-services_68.html

When I reverse my google search, I'm not finding much support for "maximum log level" being used to indicate "show debug through to fatal", "show warn through to fatal", etc.

**Comment by driskell** [comment]
I see now. When I hear "log level" - I think about quantity (level) of logs and not severity (level) of logs. So the minimum log level would be critical, always, since that's the least detailed and least often expected.

If I think, "log severity", I see it now. Maximum log severity makes no sense. Minimum log severity does.

How interesting :-)

**Comment by tedder** [comment]
I see what you mean about "severity", though I always thought of "level" as stairs, basically. I guess that works if the stairs/steps are on a pyramid- higher levels mean less "area".

Ahh, language.

**Pull request merged**
